updated_array = using_push(colors_in_the_rainbow, next_color)
@updated_array = using_unshift(bouroughs_in_nyc, @new_neighborhood)
@updated_array = using_unshift(bouroughs_in_nyc, @new_neighborhood)
@deleted_string = using_pop(@continents)
@deleted_string = using_pop(@continents)